### PR TITLE
Add Scheduled Jobs metrics

### PR DESCRIPTION
**Pull request by volodymyr-mykhailyk**

### CODE REVIEW

**Comment by volodymyr-mykhailyk** [comment]
@dfuentes77 If these changes looks good - I will merge and release new version

**Comment by dfuentes77** [comment]
I'm getting this error when launching Sidekiq with these changes, and it fails to start:
```
Feb 17 00:22:15 ip-10-3-19-189 sidekiq[792255]: I, [2023-02-17T00:22:15.459965 #792255]  INFO -- : Booting Sidekiq 5.1.3 with redis options {:url=>"redis://<redis host>:6379", :id=>"Sidekiq-server-PID-792255"}
Feb 17 00:22:15 ip-10-3-19-189 sidekiq[792255]: undefined method `[]' for Sidekiq:Module
Feb 17 00:22:15 ip-10-3-19-189 sidekiq[792255]: ...bundler/gems/sidekiq-datadog-monitor-e62115da881f/lib/sidekiq/datadog/monitor/heartbeat_patch.rb:27:in `needs_patching?'
Feb 17 00:22:15 ip-10-3-19-189 sidekiq[792255]: .../bundler/gems/sidekiq-datadog-monitor-e62115da881f/lib/sidekiq/datadog/monitor.rb:69:in `patch_sidekiq_heartbeat'
Feb 17 00:22:15 ip-10-3-19-189 sidekiq[792255]: .../bundler/gems/sidekiq-datadog-monitor-e62115da881f/lib/sidekiq/datadog/monitor.rb:54:in `block in add_sidekiq_listeners'
Feb 17 00:22:15 ip-10-3-19-189 sidekiq[792255]: .../2.6.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:73:in `configure_server'
```

**Comment by volodymyr-mykhailyk** [comment]
@dfuentes77 Merged the latest changes from the master into this branch. This issue is fixed as well.

**Comment by dfuentes77** [comment]
Sorry, I haven't been able to test it yet but I'll be looking at it soon.  Thanks!

**Comment by volodymyr-mykhailyk** [comment]
@dfuentes77 Any updates on these changes? BTW latest version of gem is working for couple weeks in our production environment without any issues.

**Comment by dfuentes77** [comment]
> @dfuentes77 Any updates on these changes? BTW latest version of gem is working for couple weeks in our production environment without any issues.

@volodymyr-mykhailyk Thank you for your patience.  I was just able to test your latest master and these branch commits merged on top and I'm seeing all the metrics as expected.  Thank you again for the work.  Feel free to merge in as you see fit.  I appreciate the assistance with this new metric.

**Comment by volodymyr-mykhailyk** [comment]
New release https://github.com/matic-insurance/sidekiq-datadog-monitor/releases/tag/1.1.0 should be published to rubygems

**Pull request merged**
